export const StreamData = [
  {
    course: "Information Technology",
    color: "#370d59",
    id: 1,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "COE",
    color: "red",
    id: 2,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "ECE",
    color: "#370d59",
    id: 3,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#370d59",
    id: 4,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#370d59",
    id: 5,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#370d59",
    id: 6,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#370d59",
    id: 7,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
  {
    course: "Information Technology",
    color: "#370d59",
    id: 8,
    links: {
      sem1: "https://www.google.com/",
      sem2: "https://www.google.com/",
      sem3: "https://www.facebook.com/",
      sem4: "https://www.facebook.com/",
      sem5: "https://www.facebook.com/",
      sem6: "https://www.facebook.com/",
      sem7: "https://www.facebook.com/",
      sem8: "https://www.facebook.com/",
    },
  },
];
